on:
  schedule:
    - cron: "* * * * *"

jobs:
  hi:
    name: TEST
    runs-on: ubuntu-latest
    strategy:
    matrix:
    branch:
      - dev
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branc }}
      - run: echo I've checked out the `${{ matrix.branch }}` branch
